x-airflow-common: &airflow-common
  build:
    context: ./airflow
    dockerfile: Dockerfile
  env_file: ./.env.airflow
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/crypto_db
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/crypto_db
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: America/Buenos_Aires
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/scripts:/opt/airflow/scripts
    - ../airflow/logs:/opt/airflow/logs
    - ../database/sql/init:/opt/airflow/sql
    - ../airflow/ge:/opt/airflow/ge
  depends_on:
    - postgres
    - redis
    - minio
    - minio-mc

services:
  postgres:
    build:
      context: ./postgres
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/sql/init:/docker-entrypoint-initdb.d

  pgadmin:
    build:
      context: ./pgadmin
    container_name: crypto_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  redis:
    build:
      context: ./redis
    container_name: crypto_redis

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    container_name: crypto_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-mc:
    build:
      context: ./minio
      dockerfile: Dockerfile.mc
    container_name: crypto_minio_mc
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: -c "/create_buckets.sh && sleep infinity"
    volumes:
      - ./minio/create_buckets.sh:/create_buckets.sh:ro

  airflow-init:
    <<: *airflow-common
    container_name: crypto_airflow_init
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --firstname Air --lastname Flow --role Admin --email admin@example.com --password admin || true"
    depends_on:
      - postgres
      - redis

  airflow-webserver:
    <<: *airflow-common
    container_name: crypto_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    container_name: crypto_airflow_scheduler
    command: scheduler
    restart: unless-stopped
    depends_on:
      - airflow-init

  airflow-worker:
    <<: *airflow-common
    container_name: crypto_airflow_worker
    command: celery worker
    restart: unless-stopped
    depends_on:
      - airflow-init

volumes:
  postgres_data:
  minio_data:
